name: Multiple Events

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  event_triger_Job:
    runs-on: ubuntu-latest
    steps:
      - name: "Way to event (shows on heading)"
        run: echo "Hi"

